### ISSUE TITLE
New MEGA Naming convention issue / path not found

### ISSUE THREAD

**Issue by dtschmitz** [ValHue/AUR-PKGBUILDs#2]
Hey thanks for all your hard work.

The MEGA nautilus-megasync is found in a different path than pkgbuild is looking, thus it errors out:

/******
wget https://mega.nz/linux/MEGAsync/Debian_8.0/amd64/nautilus-megasync-Debian_8.0_amd64.deb
--2015-07-31 11:49:13--  https://mega.nz/linux/MEGAsync/Debian_8.0/amd64/nautilus-megasync-Debian_8.0_amd64.deb
Resolving mega.nz (mega.nz)... 154.53.224.166, 2001:978:2:aa::29:2
Connecting to mega.nz (mega.nz)|154.53.224.166|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 47570 (46K) [application/x-deb]
Saving to: ‘nautilus-megasync-Debian_8.0_amd64.deb’

nautilus-megasync-D 100%[=====================>]  46.46K  --.-KB/s   in 0.1s   

2015-07-31 11:49:15 (315 KB/s) - ‘nautilus-megasync-Debian_8.0_amd64.deb’ saved [47570/47570]

******/

Also the sha256sum is different:
/*****
[dts@ThinkPad Downloads]$ sha256sum nautilus-megasync-Debian_8.0_amd64.deb 
06470c7e342c474d9a87afa1a7cdef2d14fc5e2bcd18d61438edb23718c0dbe1  nautilus-megasync-Debian_8.0_amd64.deb
[dts@ThinkPad Downloads]$ 

*****/

Please update accordingly.  Thank you!
Dietrich T. Schmitz
DTS & Associates.com
dietrich@dtschmitz.com

**Comment by ValHue** [comment]
All these errors are because the updater Manjaro connected to https://aur.archlinux.org/ rather than to https://aur4.archlinux.org/

Fortunately already it completed the transition to AUR4 and no need to change to the previous URL.

I close the thread
