### ISSUE TITLE
New MEGA naming convention / path not found 

### ISSUE THREAD

**Issue by dtschmitz** [ValHue/AUR-PKGBUILDs#3]
Hi,

The path to megasync client has changed.

It's the same issue that I just reported on nautilus-megasync:
https://github.com/ValHue/AUR-PKGBUILDs/issues/3

Naturally, the sha256sum will change also.

Please correct at your earliest opportunity and thanks for your hard work.

Dietrich T. Schmitz
DTS & Associates
dietrich@dtschmitz.com

**Comment by ValHue** [comment]
All these errors are because the updater Manjaro connected to https://aur.archlinux.org/ rather than to https://aur4.archlinux.org/

Fortunately already it completed the transition to AUR4 and no need to change to the previous URL.

I close the thread
