### ISSUE TITLE
Arch package management senses an update but errors due to issue #2 and #3

### ISSUE THREAD

**Issue by dtschmitz** [ValHue/AUR-PKGBUILDs#4]
Hi,
I submitted issues #2 and #3 today.
I temporarily fixed the pkgbuild so I could install those two packages see attached screenshot.

But now the package manager 'thinks' I need two more updates
![screenshot from 2015-07-31 12-13-50](https://cloud.githubusercontent.com/assets/33075/9011842/132c46d8-377e-11e5-8dae-42cb841e1256.png)

This should be resolved I assume when you've taken care of those 2 issues.

Thank you.
Dietrich T. Schmitz
DTS & Associates
dietrich@dtschmitz.com

**Comment by ValHue** [comment]
All these errors are because the updater Manjaro connected to https://aur.archlinux.org/ rather than to https://aur4.archlinux.org/

Fortunately already it completed the transition to AUR4 and no need to change to the previous URL.

I close the thread
